/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
	"gardenmanager adapter settings": {
		en: "Adapter settings for gardenmanager",
		de: "Adaptereinstellungen für gardenmanager",
		ru: "Настройки адаптера для gardenmanager",
		pt: "Configurações do adaptador para gardenmanager",
		nl: "Adapterinstellingen voor gardenmanager",
		fr: "Paramètres d'adaptateur pour gardenmanager",
		it: "Impostazioni dell'adattatore per gardenmanager",
		es: "Ajustes del adaptador para gardenmanager",
		pl: "Ustawienia adaptera dla gardenmanager",
		uk: "Налаштування адаптера для gardenmanager",
		"zh-cn": "gardenmanager的适配器设置",
	},
	option1: {
		en: "option1",
		de: "option1",
		ru: "option1",
		pt: "option1",
		nl: "option1",
		fr: "option1",
		it: "option1",
		es: "option1",
		pl: "option1",
		uk: "option1",
		"zh-cn": "option1",
	},
	option2: {
		en: "option2",
		de: "option2",
		ru: "option2",
		pt: "option2",
		nl: "option2",
		fr: "option2",
		it: "option2",
		es: "option2",
		pl: "option2",
		uk: "option2",
		"zh-cn": "option2",
	},
	myColor: {
		en: "myColor",
		de: "meineColor",
		ru: "Мой цвет",
		pt: "minhaCor",
		nl: "mijnKleur",
		fr: "maCouleur",
		it: "mioColore",
		es: "miColor",
		pl: "mójKolor",
		uk: "мійКолір",
		"zh-cn": "我的颜色",
	},
	myColor_tooltip: {
		en: "Description of\nmyColor",
		de: "Beschreibung von\nmyColor",
		ru: "Описание\nmyColor",
		pt: "Descrição de\nmyColor",
		nl: "Beschrijving van\nmyColor",
		fr: "Description de\nmyColor",
		it: "Descrizione di\nmyColor",
		es: "Descripción de\nmyColor",
		pl: "Opis\nmyColor",
		uk: "Опис\nmyColor",
		"zh-cn": "\nmyColor的描述",
	},
	htmlText: {
		en: "htmlText",
		de: "htmlText",
		ru: "htmlText",
		pt: "htmlText",
		nl: "htmlText",
		fr: "htmlText",
		it: "htmlText",
		es: "htmlText",
		pl: "htmlText",
		uk: "htmlText",
		"zh-cn": "htmlText",
	},
	group_extraMyset: {
		en: "extraMyset",
		de: "extraMyset",
		ru: "extraMyset",
		pt: "extraMyset",
		nl: "extraMyset",
		fr: "extraMyset",
		it: "extraMyset",
		es: "extraMyset",
		pl: "extraMyset",
		uk: "extraMyset",
		"zh-cn": "extraMyset",
	},
	extraAttr: {
		en: "extraAttr",
		de: "extraAttr",
		ru: "extraAttr",
		pt: "extraAttr",
		nl: "extraAttr",
		fr: "extraAttr",
		it: "extraAttr",
		es: "extraAttr",
		pl: "extraAttr",
		uk: "extraAttr",
		"zh-cn": "extraAttr",
	},
	Instance: {
		en: "Instance",
		de: "Instanz",
		ru: "Инстанция",
		pt: "Instância",
		nl: "Instantie",
		fr: "Instance",
		it: "Esempio",
		es: "Instancia",
		pl: "Instancja",
		uk: "Інстанція",
		"zh-cn": "例",
	},
};
